/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_ifmo_se_jni_NativeMathJni */

#ifndef _Included_ru_ifmo_se_jni_NativeMathJni
#define _Included_ru_ifmo_se_jni_NativeMathJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_ifmo_se_jni_NativeMathJni
 * Method:    computeAverageValue
 * Signature: ([FI)F
 */
JNIEXPORT jfloat JNICALL Java_ru_ifmo_se_jni_NativeMathJni_computeAverageValue
  (JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     ru_ifmo_se_jni_NativeMathJni
 * Method:    computeEuclideanDistance
 * Signature: ([F[FI)F
 */
JNIEXPORT jfloat JNICALL Java_ru_ifmo_se_jni_NativeMathJni_computeEuclideanDistance
  (JNIEnv *, jobject, jfloatArray, jfloatArray, jint);

/*
 * Class:     ru_ifmo_se_jni_NativeMathJni
 * Method:    computeAngularDistance
 * Signature: ([F[FI)F
 */
JNIEXPORT jfloat JNICALL Java_ru_ifmo_se_jni_NativeMathJni_computeAngularDistance
  (JNIEnv *, jobject, jfloatArray, jfloatArray, jint);

/*
 * Class:     ru_ifmo_se_jni_NativeMathJni
 * Method:    computeDispersion
 * Signature: ([FI)F
 */
JNIEXPORT jfloat JNICALL Java_ru_ifmo_se_jni_NativeMathJni_computeDispersion
  (JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     ru_ifmo_se_jni_NativeMathJni
 * Method:    computeAverageVector
 * Signature: ([FII)[F
 */
JNIEXPORT jfloatArray JNICALL Java_ru_ifmo_se_jni_NativeMathJni_computeAverageVector
  (JNIEnv *, jobject, jfloatArray, jint, jint);

/*
 * Class:     ru_ifmo_se_jni_NativeMathJni
 * Method:    computeEuclideanDistanceMulti
 * Signature: ([F[FII)[F
 */
JNIEXPORT jfloatArray JNICALL Java_ru_ifmo_se_jni_NativeMathJni_computeEuclideanDistanceMulti
  (JNIEnv *, jobject, jfloatArray, jfloatArray, jint, jint);

/*
 * Class:     ru_ifmo_se_jni_NativeMathJni
 * Method:    computeAngularDistanceMulti
 * Signature: ([F[FII)[F
 */
JNIEXPORT jfloatArray JNICALL Java_ru_ifmo_se_jni_NativeMathJni_computeAngularDistanceMulti
  (JNIEnv *, jobject, jfloatArray, jfloatArray, jint, jint);

/*
 * Class:     ru_ifmo_se_jni_NativeMathJni
 * Method:    computeEuclideanDistanceMatrix
 * Signature: ([FII)[F
 */
JNIEXPORT jfloatArray JNICALL Java_ru_ifmo_se_jni_NativeMathJni_computeEuclideanDistanceMatrix
  (JNIEnv *, jobject, jfloatArray, jint, jint);

/*
 * Class:     ru_ifmo_se_jni_NativeMathJni
 * Method:    computeAngularDistanceMatrix
 * Signature: ([FII)[F
 */
JNIEXPORT jfloatArray JNICALL Java_ru_ifmo_se_jni_NativeMathJni_computeAngularDistanceMatrix
  (JNIEnv *, jobject, jfloatArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
